name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production          # ensure prod build (no dev-only paths)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (uses astro.config site/base)
        run: npx astro build

      - name: Show dist tree (first 300 lines)
        run: |
          echo "---- dist (first 300 files) ----"
          find dist -type f | sed -n '1,300p'

      # If you rely on runtime JSON fetches, you may still emit dist/locales.
      # That's optional when translations are inlined at build time.
      - name: Validate baked translations (fail if keys leaked)
        run: |
          echo "Checking that translation KEYS are not present in built HTML..."
          # Add or adjust the key patterns below to match your usage.
          set -e
          if grep -R -nE 'global\.headerHome|index\.heroTitle' dist; then
            echo "❌ Found raw i18n KEYS in built output. Build did not bake translations."
            exit 1
          else
            echo "✅ No raw i18n keys found in built output."
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
